### ISSUE TITLE
Example menus link to #

### ISSUE THREAD

**Issue by droundy** [bitfragment/mindoc#2]
In the linked examples, the menu does not link to the relevant sections.

**Comment by droundy** [comment]
I take this back.  I see now that the menus change the page to only show the selected section. This was hard to notice because only the first line or so of the section was visible. I expected the page to scroll such that I could read the section.

**Comment by bitfragment** [comment]
Thanks. I can certainly see the issue. I myself prefer that the menu remain in place with the active item highlighted, rather than having the menu scroll out of sight, which I find disorienting especially on a phone. The obvious alternatives (a horizontal menu or hamburger/tribar button) don't work for me either.
